/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChangeApplicability } from '../change-applicability.model';

export interface ApplicabilitiesUpdate {
  /**
   * The ids which their applicability updated successfully
   */
  true: ChangeApplicability[];

  /**
   * The ids which their applicability failed to update
   */
  false: ChangeApplicability[];
}
