/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ApproverInstance {
    /**
     * name of the user (approvaer/reviwer)
     */
    name?: string;
    /**
     * email of the user (approvaer/reviwer)
     */
    email?: string;
    /**
     * role of the user (approvaer/reviwer)
     */
    role?: string;
    comments?: string;
    last_notified?: string;

    readonly approved?: boolean;
    readonly approved_time?: Date;
}
