/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DocumentEvidenceInstance } from './documentEvidenceInstance';
import { EvidenceInstance } from './evidenceInstance';
import { ManualEvidenceInstance } from './manualEvidenceInstance';

export interface CombinedEvidenceInstance extends EvidenceInstance {
  /**
   * This manual evidence was uploaded by this user
   */
  evidence_uploaded_by?: string;
  /**
   * The last modification time of this document
   */
  evidence_last_modified_time?: Date;
  /**
   * The last modificator of this document
   */
  evidence_last_modified_by?: string;
}
