/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The data structure that describes a specific control and its related frameworks with its respective control names
 */
export interface ControlRelatedFramework {
  /**
   * The related framework name
   */
  framework_name?: string;
  /**
   * The respective control names from the specific related framework
   */
  respective_controls?: Array<string>;
}
