/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ControlStatus } from './controlStatus';

export interface CustomControl { 
    /**
     * The control unique ID
     */
    readonly control_id?: string;
    /**
     * The control name
     */
    control_name?: string;
    /**
     * The control description
     */
    control_description?: string;
    /**
     * creator framework catgeory
     */
    control_framework_category?: string;
    /**
     * framework category for my controls framework, if not main framework
     */
    my_controls_category?: string;
    /**
     * List of original controls related controls
     */
    control_original_related_controls?: Array<string>;
    control_status?: ControlStatus;
    /**
     * The email of control's owner
     */
    control_owner?: string;
}
