/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the customer/company and all the metadata we keep
 */
export interface Customer {
  /**
   * The customer/company name
   */
  customer_name?: string;
  /**
   * A URL that contains the logo related with this customer
   */
  customer_logo?: string;

  /**
   * whether the customer has onboarded or not
   */
  is_onboarded?: boolean;

  /**
   * list of features the customer can access
   */
  account_features?: AccountFeatureEnum[];

  /**
   * The Account type of the customer
   */
  account_type?: string;
}


export type AccountFeatureEnum = 'Adopt framework' | 'Audit zone' | 'Run on demand' | 'Reports' | 'Policy Templates' | 'Export controls';
export const AccountFeatureEnum = {
  AdoptFramework: 'Adopt framework' as AccountFeatureEnum,
  AuditZone: 'Audit zone' as AccountFeatureEnum,
  RunOnDemand: 'Run on demand' as AccountFeatureEnum,
  Reports: 'Reports' as AccountFeatureEnum,
  PolicyTemplates: 'Policy Templates' as AccountFeatureEnum,
  ExportControls: 'Export controls' as AccountFeatureEnum
};
