/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EvidenceInstance } from './evidenceInstance';

export interface DocumentEvidenceInstance extends EvidenceInstance {
  /**
   * The last modification time of this document
   */
  evidence_last_modified_time?: Date;
  /**
   * The last modificator of this document
   */
  evidence_last_modified_by?: string;
}
