/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface PolicyShare { 
   /**
    * The email of the external user to create the link/mail(/etc...) for
    */
   user_email?: string;
   /**
    * The way of sharing. Copy link, send it by mail, etc...
    */
   share_method?: ShareMethodEnum;
   /**
    * Custom message to include with sharing via messaging platforms (mail, slack, etc..)
    */
   message?: string;
   approver_type?: ApproverTypeEnum;
}

export type ShareMethodEnum = 'email' | 'link';
export const ShareMethodEnum = {
    Email: 'email' as ShareMethodEnum,
    Link: 'link' as ShareMethodEnum
};
export type ApproverTypeEnum = 'owner' | 'reviewer' | 'approver';
export const ApproverTypeEnum = {
    Owner: 'owner' as ApproverTypeEnum,
    Reviewer: 'reviewer' as ApproverTypeEnum,
    Approver: 'approver' as ApproverTypeEnum
};
