/**
 * Anecdotes API
 * Anecdotes API's
 *
 * OpenAPI spec version: 0.0.3
 * Contact: apiteam@anecdotes.ai
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ServiceLog {
  /**
   * the id of the specific run
   */
  run_id?: string;
  /**
   * the log message
   */
  message?: string;
  /**
   * the log level (debug/info/etc)
   */
  severity?: string;
  /**
   * the time of the message
   */
  timestamp?: number;
}
